spring:
  application:
    name: addressapiv1
    
  datasource:
    url: jdbc:mysql://localhost:3306/university
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8082
