spring:
  application:
    name: addressapiv3
    
  datasource:
    url: jdbc:mysql://localhost:3306/university
    username: root
    password: Maheb052002
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka      

server:
  port: 8082
